version: "3.4"

services:
  janusgraphserver:
    image: janusgraphserver
    container_name: janusgraphserver
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API: https://api.ioak.io:8010
      PORT: 8025
    ports:
      - 8025:8025
    networks:
      ioak-net:
        aliases:
          - janusgraphserver.docker

networks:
  ioak-net:
    name: ioak-network
